name: Build ESP32-C3 Firmware

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@2.0.17

      - name: Install Libraries
        run: |
          arduino-cli lib install "Adafruit MPU6050"
          arduino-cli lib install "Adafruit Unified Sensor"

      - name: Prepare Sketch
        run: |
          mkdir drone
          cp drone.ino drone/drone.ino

      - name: Compile
        run: |
          arduino-cli compile \
          --fqbn esp32:esp32:esp32c3 \
          --output-dir build \
          drone

      - name: Upload BIN
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin
